title: Sushmitha Jagannath
logo: /images/profile.jpeg
#description: text below image
#show_downloads: true
show_github: false
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
show_github_link: false
